# Generated by Django 4.2.8 on 2025-04-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('tax_code', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('landline_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_notes', models.TextField(blank=True, null=True)),
                ('supplier_status', models.BooleanField(default=True)),
                ('supplier_created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50, unique=True)),
                ('unit_notes', models.TextField(blank=True, null=True)),
                ('unit_status', models.BooleanField(default=True)),
                ('unit_created_at', models.DateTimeField(auto_now_add=True)),
                ('unit_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
