# Generated by Django 4.2.8 on 2025-05-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
