# Generated by Django 4.2.8 on 2025-05-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockb', '0002_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Kích hoạt'), ('UNACTIVE', 'Tắt kích hoạt')], default='ACTIVE', max_length=20),
        ),
    ]
