# Generated by Django 4.2.8 on 2025-05-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockb', '0003_productdetail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='product_batch',
        ),
    ]
