# Generated by Django 4.2.8 on 2025-05-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockb', '0005_alter_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='import_status',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='export_status',
        ),
    ]
