# Generated by Django 4.2.8 on 2025-05-05 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockb', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='stock_in_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='stockb.stockindetail'),
        ),
    ]
