# Generated by Django 4.2.8 on 2025-05-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockb', '0010_alter_productdetail_stock_in_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='stock_in_detail',
        ),
        migrations.AddField(
            model_name='stockindetail',
            name='product_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockb.productdetail'),
        ),
    ]
