# Generated by Django 4.2.8 on 2025-05-06 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockb', '0011_remove_productdetail_stock_in_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockindetail',
            name='import_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stockb.stockin'),
        ),
        migrations.AlterField(
            model_name='stockindetail',
            name='product_detail',
            field=models.OneToOneField(default=19, on_delete=django.db.models.deletion.CASCADE, to='stockb.productdetail'),
            preserve_default=False,
        ),
    ]
