# Generated by Django 4.2.8 on 2025-05-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockb', '0012_alter_stockindetail_import_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockb.product'),
        ),
        migrations.AlterField(
            model_name='stockindetail',
            name='product_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_details', to='stockb.productdetail'),
        ),
    ]
