# Generated by Django 5.1.6 on 2025-04-29 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Danh mục sản phẩm', 'verbose_name_plural': 'Danh mục sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Nhà cung cấp', 'verbose_name_plural': 'Nhà cung cấp'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Đơn vị', 'verbose_name_plural': 'Đơn vị'},
        ),
        migrations.AlterUniqueTogether(
            name='inventorycheckdetail',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productdetail',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='inventorycheck',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventorycheck',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='import_status',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='stockindetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stockindetail',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='stockindetail',
            name='product_batch',
        ),
        migrations.RemoveField(
            model_name='stockindetail',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='stockoutdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stockoutdetail',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tax_code',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_symbol',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='update_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='stockindetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='inventorycheckdetail',
            name='product_batch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockb.productcategory', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inspection_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kiểm tra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.IntegerField(default=0, verbose_name='Số lượng tồn kho tối thiểu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá nhập vào'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá bán ra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockb.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockb.unit', verbose_name='Đơn vị'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(max_length=255, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='import_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_batch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='import_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='export_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='export_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Đang xử lý'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Hủy bỏ')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Đã thanh toán'), ('UNPAID', 'Chưa thanh toán')], default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockoutdetail',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Tên công ty'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=50, verbose_name='Tên đơn vị'),
        ),
        migrations.RemoveField(
            model_name='inventorycheckdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventorycheckdetail',
            name='discrepancy',
        ),
        migrations.RemoveField(
            model_name='inventorycheckdetail',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='initial_quantity',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='stock_in_detail',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='update_at',
        ),
    ]
