# Generated by Django 4.2.8 on 2025-05-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockb', '0006_remove_stockin_import_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='stockin',
            name='amount_paid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
