# Generated by Django 4.2.8 on 2025-05-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockb', '0007_remove_stockin_total_amount_stockin_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycheckdetail',
            name='product_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockb.productdetail'),
        ),
    ]
