from django.urls import path
from stockb import views

urlpatterns = [
    path('', views.index, name='index'),
    path('product/', views.product_view, name='product'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('product/create/', views.product_update, name='product_create'),
    path('product/<int:pk>/update/', views.product_update, name='product_update'),
    path('product/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('product-category/', views.product_category_view, name='product_category'),
    path('product-category/create/', views.product_category_create, name='product_category_create'),
    path('product-category/<int:pk>/', views.product_category_detail, name='product_category_detail'),
    path('product-category/<int:pk>/update/', views.product_category_update, name='product_category_update'),
    path('product-category/<int:pk>/delete/', views.product_category_delete, name='product_category_delete'),
    path('stock-out/', views.stock_out, name='stock_out'),
    path('stock-out/create/', views.stock_out_update, name='stock_out_create'),
    path('stock-out/<int:pk>/update/', views.stock_out_update, name='stock_out_update'),
    path('stock-in/', views.stock_in, name='stock_in'),
    path('stock-in/create/', views.stock_in_update, name='stock_in_create'),
    path('supplier/', views.supplier_list_view, name='supplier_list'),
    path('supplier/create/', views.supplier_create_view, name='supplier_create'),
    path('near-expiry/', views.near_expiry_list_view, name='near_expiry_list'),
    path('low-stock/', views.low_stock_list_view, name='low_stock_list'),
    path('units/', views.units_view, name='units'),
    path('units/create/', views.create_unit, name='create_unit'),
    path('report/', views.report_overview, name='report_overview'),
    path('customer/', views.customer_list, name='customer_list'),
    path('customer/create/', views.customer_create, name='customer_create'),
    path('employee/', views.employee_list, name='employee_list'),
    path('employee/create/', views.employee_create, name='employee_create'),
    path('inventory-check/', views.inventory_check_list, name='inventory_check_list'),
    path('inventory-check/create/', views.inventory_check_create, name='inventory_check_create'),
    path('inventory-check/<int:pk>/update/', views.inventory_check_update, name='inventory_check_update'),
    path('inventory-check/<int:pk>/delete/', views.inventory_check_delete, name='inventory_check_delete'),
]